/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CommoditiesRouteImport } from './routes/commodities'
import { Route as CoursePricingRouteImport } from './routes/course-pricing'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FdRouteImport } from './routes/fd'
import { Route as FoRouteImport } from './routes/fo'
import { Route as FreeCoursesRouteImport } from './routes/free-courses'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as MarketNewsRouteImport } from './routes/market-news'
import { Route as MutualFundsRouteImport } from './routes/mutual-funds'
import { Route as OperationalCostRouteImport } from './routes/operational-cost'
import { Route as PortfolioRouteImport } from './routes/portfolio'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const MarketsRoute = MarketsRouteImport.update({ id: '/markets', path: '/markets', getParentRoute: () => rootRouteImport } as any)
const OrdersRoute = OrdersRouteImport.update({ id: '/orders', path: '/orders', getParentRoute: () => rootRouteImport } as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const CommoditiesRoute = CommoditiesRouteImport.update({ id: '/commodities', path: '/commodities', getParentRoute: () => rootRouteImport } as any)
const CoursePricingRoute = CoursePricingRouteImport.update({ id: '/course-pricing', path: '/course-pricing', getParentRoute: () => rootRouteImport } as any)
const CoursesRoute = CoursesRouteImport.update({ id: '/courses', path: '/courses', getParentRoute: () => rootRouteImport } as any)
const FdRoute = FdRouteImport.update({ id: '/fd', path: '/fd', getParentRoute: () => rootRouteImport } as any)
const FoRoute = FoRouteImport.update({ id: '/fo', path: '/fo', getParentRoute: () => rootRouteImport } as any)
const FreeCoursesRoute = FreeCoursesRouteImport.update({ id: '/free-courses', path: '/free-courses', getParentRoute: () => rootRouteImport } as any)
const InvestmentsRoute = InvestmentsRouteImport.update({ id: '/investments', path: '/investments', getParentRoute: () => rootRouteImport } as any)
const MarketNewsRoute = MarketNewsRouteImport.update({ id: '/market-news', path: '/market-news', getParentRoute: () => rootRouteImport } as any)
const MutualFundsRoute = MutualFundsRouteImport.update({ id: '/mutual-funds', path: '/mutual-funds', getParentRoute: () => rootRouteImport } as any)
const OperationalCostRoute = OperationalCostRouteImport.update({ id: '/operational-cost', path: '/operational-cost', getParentRoute: () => rootRouteImport } as any)
const PortfolioRoute = PortfolioRouteImport.update({ id: '/portfolio', path: '/portfolio', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/orders': typeof OrdersRoute
  '/account': typeof AccountRoute
  '/commodities': typeof CommoditiesRoute
  '/course-pricing': typeof CoursePricingRoute
  '/courses': typeof CoursesRoute
  '/fd': typeof FdRoute
  '/fo': typeof FoRoute
  '/free-courses': typeof FreeCoursesRoute
  '/investments': typeof InvestmentsRoute
  '/market-news': typeof MarketNewsRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/operational-cost': typeof OperationalCostRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/orders': typeof OrdersRoute
  '/account': typeof AccountRoute
  '/commodities': typeof CommoditiesRoute
  '/course-pricing': typeof CoursePricingRoute
  '/courses': typeof CoursesRoute
  '/fd': typeof FdRoute
  '/fo': typeof FoRoute
  '/free-courses': typeof FreeCoursesRoute
  '/investments': typeof InvestmentsRoute
  '/market-news': typeof MarketNewsRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/operational-cost': typeof OperationalCostRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: '__root__' | keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  OrdersRoute: typeof OrdersRoute
  AccountRoute: typeof AccountRoute
  CommoditiesRoute: typeof CommoditiesRoute
  CoursePricingRoute: typeof CoursePricingRoute
  CoursesRoute: typeof CoursesRoute
  FdRoute: typeof FdRoute
  FoRoute: typeof FoRoute
  FreeCoursesRoute: typeof FreeCoursesRoute
  InvestmentsRoute: typeof InvestmentsRoute
  MarketNewsRoute: typeof MarketNewsRoute
  MutualFundsRoute: typeof MutualFundsRoute
  OperationalCostRoute: typeof OperationalCostRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/markets': { id: '/markets'; path: '/markets'; fullPath: '/markets'; preLoaderRoute: typeof MarketsRouteImport; parentRoute: typeof rootRouteImport }
    '/orders': { id: '/orders'; path: '/orders'; fullPath: '/orders'; preLoaderRoute: typeof OrdersRouteImport; parentRoute: typeof rootRouteImport }
    '/account': { id: '/account'; path: '/account'; fullPath: '/account'; preLoaderRoute: typeof AccountRouteImport; parentRoute: typeof rootRouteImport }
    '/commodities': { id: '/commodities'; path: '/commodities'; fullPath: '/commodities'; preLoaderRoute: typeof CommoditiesRouteImport; parentRoute: typeof rootRouteImport }
    '/course-pricing': { id: '/course-pricing'; path: '/course-pricing'; fullPath: '/course-pricing'; preLoaderRoute: typeof CoursePricingRouteImport; parentRoute: typeof rootRouteImport }
    '/courses': { id: '/courses'; path: '/courses'; fullPath: '/courses'; preLoaderRoute: typeof CoursesRouteImport; parentRoute: typeof rootRouteImport }
    '/fd': { id: '/fd'; path: '/fd'; fullPath: '/fd'; preLoaderRoute: typeof FdRouteImport; parentRoute: typeof rootRouteImport }
    '/fo': { id: '/fo'; path: '/fo'; fullPath: '/fo'; preLoaderRoute: typeof FoRouteImport; parentRoute: typeof rootRouteImport }
    '/free-courses': { id: '/free-courses'; path: '/free-courses'; fullPath: '/free-courses'; preLoaderRoute: typeof FreeCoursesRouteImport; parentRoute: typeof rootRouteImport }
    '/investments': { id: '/investments'; path: '/investments'; fullPath: '/investments'; preLoaderRoute: typeof InvestmentsRouteImport; parentRoute: typeof rootRouteImport }
    '/market-news': { id: '/market-news'; path: '/market-news'; fullPath: '/market-news'; preLoaderRoute: typeof MarketNewsRouteImport; parentRoute: typeof rootRouteImport }
    '/mutual-funds': { id: '/mutual-funds'; path: '/mutual-funds'; fullPath: '/mutual-funds'; preLoaderRoute: typeof MutualFundsRouteImport; parentRoute: typeof rootRouteImport }
    '/operational-cost': { id: '/operational-cost'; path: '/operational-cost'; fullPath: '/operational-cost'; preLoaderRoute: typeof OperationalCostRouteImport; parentRoute: typeof rootRouteImport }
    '/portfolio': { id: '/portfolio'; path: '/portfolio'; fullPath: '/portfolio'; preLoaderRoute: typeof PortfolioRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  MarketsRoute,
  OrdersRoute,
  AccountRoute,
  CommoditiesRoute,
  CoursePricingRoute,
  CoursesRoute,
  FdRoute,
  FoRoute,
  FreeCoursesRoute,
  InvestmentsRoute,
  MarketNewsRoute,
  MutualFundsRoute,
  OperationalCostRoute,
  PortfolioRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
